### PR TITLE
Stormspeed refined mesh capability now running

### LINKED ISSUE #40: variable resolution fails
### What happened?

more detailed from UMICH

### What are the steps to reproduce the bug?

Run model

### What CAM tag were you using?

.

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

_No response_

### Will you be addressing this bug yourself?

No

### Extra info

_No response_

### PR DESCRIPTION
**Pull request by jtruesdal**
This PR enables refined mesh capability in the stormspeed dynamics and updates default configurations for high-resolution ne240 grids. The changes involve moving refined mesh variables outside compiler directives, adding proper initialization and error checking, and updating CMEPS component defaults.

- Refined mesh functionality is now properly enabled by moving variables outside conditional compilation blocks
- Default time steps and viscosity parameters for ne240 and regional grid configurations are updated.  
  - As our collaborators are testing some high resolution configurations I thought it would be good to have ne240 working here. These will be folded into the official CMEPs repository in the near future.   This PR closes #40.

### CODE REVIEW

File: src/dynamics/senh/dyn_comp.F90 [hunk 1]
```diff
@@ -972,7 +901,6 @@ subroutine read_inidat(dyn_in)
   use microp_driver,           only: microp_driver_implements_cnst, microp_driver_init_cnst
   use phys_control,            only: phys_getopts
   use prim_si_mod,             only: prim_set_mass
```
[the remark this answers is not in the document]
Comment (jtruesdal) [reply src/dynamics/senh/dyn_comp.F90:876]: It's strange that copilot can't do the check itself.  Unless I am missing something a quick search of the file turns up no references to rk_stratiform* in the module.

[the remark this answers is not in the document]
Comment (jtruesdal) [reply src/dynamics/senh/dyn_comp.F90:876]: @sjsprecious I love the automated testing.

File: .gitmodules [hunk 2]
```diff
@@ -157,10 +157,10 @@ fxDONOTUSEurl = https://github.com/ESMCI/cime.git
 
 [submodule "cmeps"]
 path = components/cmeps
-url = https://github.com/ESCOMP/CMEPS.git 
-fxtag = cmeps1.1.8
+url = https://github.com/jtruesdal/CMEPS.git
+fxtag = cmeps1.1.8_refmesh.01
 fxrequired = ToplevelRequired
-fxDONOTUSEurl = https://github.com/ESCOMP/CMEPS.git 
+fxDONOTUSEurl = https://github.com/jtruesdal/CMEPS.git
```
Comment (sjsprecious) [inline .gitmodules]: Do you prefer to have a separate PR to update the CMPES tag?

File: .gitmodules [hunk 3]
```diff
@@ -157,10 +157,10 @@ fxDONOTUSEurl = https://github.com/ESMCI/cime.git
```
Comment (sjsprecious) [inline .gitmodules]: Also can we merge your ccs_config changes to the official repo now?

File: bld/namelist_files/namelist_defaults_cam.xml [hunk 4]
```diff
@@ -31,7 +31,7 @@
 <dtime dyn="se"    hgrid="ne30np4" >1800</dtime>
 <dtime dyn="se"    hgrid="ne60np4" > 900</dtime>
 <dtime dyn="se"    hgrid="ne120np4"> 450</dtime>
-<dtime dyn="se"    hgrid="ne240np4"> 225</dtime>
+<dtime dyn="se"    hgrid="ne240np4"> 450</dtime>
```
Comment (sjsprecious) [inline bld/namelist_files/namelist_defaults_cam.xml]: We don't need to reduce the dtime when going to ne240 resolution?

File: src/dynamics/senh/dyn_comp.F90 [hunk 5]
```diff
@@ -114,7 +114,10 @@ subroutine dyn_readnl(NLFileName)
   use fvm_mod,        only: fvm_get_test_type
   use native_mapping, only: native_mapping_readnl
 #endif
-  use dimensions_mod_cam, only: qsize, qsize_d, ntrac, ntrac_d, npsq, ne, npart, lcp_moist
+#ifndef HOMME_WITHOUT_PIOLIBRARY
```
Comment (sjsprecious) [inline src/dynamics/senh/dyn_comp.F90]: Where is the CPP variable being defined?

File: src/dynamics/senh/dyn_comp.F90 [hunk 6]
```diff
@@ -114,7 +114,10 @@ subroutine dyn_readnl(NLFileName)
...
+  use mesh_mod,       only: MeshOpen
```
Comment (sjsprecious) [inline src/dynamics/senh/dyn_comp.F90]: I did not find the `mesh_mod.F90` code under the `senh` folder. This code does exist under the `se/dycore` folder. Does it mean the refined mesh capacity only works with CAM-SE dycore right now?

**Review by sjsprecious — COMMENTED** [review]
Thanks @jtruesdal for working on this PR. It looks good to me and I just have a few clarification questions.

In addition, does this PR close any issue? If so, please link the PR to it.

If you think it is worthy and not expensive to run, we can include CI tests for refined mesh as well.

File: src/dynamics/senh/dyn_comp.F90 (hunk 1 above)
[the remark this answers is not in the document]
Comment (sjsprecious) [reply src/dynamics/senh/dyn_comp.F90:876]: > It's strange that copilot can't do the check itself. Unless I am missing something a quick search of the file turns up no references to rk_stratiform* in the module.

I guess you need to pay >$100 per month to get a premium Copilot who is smart enough to figure this out itself. 😄

File: src/dynamics/senh/dyn_comp.F90 (hunk 6 above)
Comment (jtruesdal) [reply src/dynamics/senh/dyn_comp.F90]: The mesh_mod.F90 file can be found at senh/dycore/components/homme/src/share/mesh_mod.F90

File: .gitmodules (hunk 3 above)
Comment (jtruesdal) [reply .gitmodules]: I will put together a ccs_config PR after this commit.

File: src/dynamics/senh/dyn_comp.F90 (hunk 5 above)
Comment (jtruesdal) [reply src/dynamics/senh/dyn_comp.F90]: This was from the E3SM code.  meshopen isn't used here anymore so I got rid of the CPP variable.

File: src/dynamics/senh/dyn_comp.F90 (hunk 6 above)
Comment (jtruesdal) [reply src/dynamics/senh/dyn_comp.F90]: I got rid of the use statement since MeshOpen isn't used here anymore.

File: .gitmodules (hunk 2 above)
Comment (jtruesdal) [reply .gitmodules]: I pulled the CMEPS update and will issue a separate PR if needed.

Comment (sjsprecious) [reply .gitmodules]: Sounds good.

File: .gitmodules (hunk 3 above)
Comment (sjsprecious) [reply .gitmodules]: Sounds good.

File: src/dynamics/senh/dyn_comp.F90 (hunk 5 above)
Comment (sjsprecious) [reply src/dynamics/senh/dyn_comp.F90]: Thanks.

File: src/dynamics/senh/dyn_comp.F90 (hunk 6 above)
Comment (sjsprecious) [reply src/dynamics/senh/dyn_comp.F90]: Thanks for your clarification.

File: bld/namelist_files/namelist_defaults_cam.xml (hunk 4 above)
Comment (sjsprecious) [reply bld/namelist_files/namelist_defaults_cam.xml]: @jtruesdal I just want to make sure that the change of the time step size here is intended.

Comment (jtruesdal) [reply bld/namelist_files/namelist_defaults_cam.xml]: Thanks I'm checking on this.  Brian Dobbins had a nonstandard set of coupling and dycore related parameter changes which worked with ne240 that used this longer ne240 physics time step.  I thought we could use that while we were debugging some of the higher resolution issues.  Now that we identified some potential issues with the topography I wanted to see if they are playing into the ne240 failure using our standard defaults (shorter physics time step.)  To be continued ...

Comment (sjsprecious) [reply bld/namelist_files/namelist_defaults_cam.xml]: Thanks John. That sounds good. Once we are clear about this change, I will go ahead and approve this PR.

Note: the CI tests on cloud are working again now.

Comment (jtruesdal) [reply bld/namelist_files/namelist_defaults_cam.xml]: @sjsprecious I believe we will need a new topography file for the ne240 and higher resolutions to be able to run with default nonhydro settings.  I've removed this change until Peter is able to provide those new files.

Comment (sjsprecious) [reply bld/namelist_files/namelist_defaults_cam.xml]: Thanks @jtruesdal . I am good with this PR for the rest changes then.

**Review by sjsprecious — APPROVED** [review]

**Comment by jtruesdal** [comment]
Thanks Jian!

jt
