### PR TITLE
Bring code up to cam6_4_100, resolve inconsistencies in ext libs, fix IC creation and restart issues

### LINKED ISSUE #51: Restart fails in QPC7 in fresh install of stormspeed branch
### What happened?

When a QPC7 run using the head of the stormspeed branch with CONTINUE_RUN=TRUE, the model crashes on restart with the error 
"20250723 143915.707 ERROR            PET314 ADDFLD:  _gll already on list
20250723 143915.772 INFO             PET314  Finalizing ESMF with endflag==ESMF_END_ABORT
20250723 143915.772 ERROR            PET314 /glade/derecho/scratch/csgteam/temp/spack/derecho/24.12/builds/spack-stage-esmf-8.8.1-oigqhlcifmbqcxchruwcjowzoxz5sa4j/spack-src/src/Infrastructure/Trace/src/ESMCI_Trace.C:1816 ESMCI::TraceEventRegionExit() Wrong argument specified  - Trace regions not properly nested exiting from region: [ESMF] Expected exit from: [ATM] IPDv03p3
20250723 143915.772 ERROR            PET314 /glade/derecho/scratch/csgteam/temp/spack/derecho/24.12/builds/spack-stage-esmf-8.8.1-oigqhlcifmbqcxchruwcjowzoxz5sa4j/spack-src/src/Infrastructure/Trace/src/ESMCI_Trace.C:1258 ESMCI::TraceClose() Wrong argument specified  - Internal subroutine call returned Error
20250723 143915.772 ERROR            PET314 ESMF_Trace.F90:102 ESMF_TraceClose() Wrong argument specified  - Internal subroutine call returned Error"

### What are the steps to reproduce the bug?

* Clone a fresh version of StormSPEED on Derecho
* Run `git checkout stormspeed`
* Run `./bin/git-fleximod update`
* The case I created is described in this [this bash script](https://github.com/OkayHughes/CESM_case_scripts/blob/main/derecho/StormSPEED/QPC7/intercompare/senh_ne30_AQP_test_stock.sh). 
* Upon creating the case and entering the case directory, run `bash xml_config_helper.sh` You should be able to reduce the number of days so it restarts sooner and get the same error.
* Build and run the case. The crash happens reliably on the first restart.

### What CAM tag were you using?

stormspeed

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

/glade/u/home/owhughes/CESM_CASE_DIRS/StormSPEED_NCAR_CASES/StormSPEED_NCAR/intercompare/StormSPEED_NCAR.ne30pg3_ne30pg3_mg17.QPC7.intercompare.senh_shallow

### Will you be addressing this bug yourself?

Yes, but I will need some help

### Extra info

This bug occurs because the call to `call read_inidat(dyn_in)` in `dyn_comp.F90` is inside of an `if (initial_run) then` conditional. As a result, the code that populates `cnst_name_gll    (m) ` and `cnst_longname_gll(m)` is not called upon restart. Moving the code that populates these fields to immediately after the `initial_run` conditional eliminates this problem. It is unclear to me if this is the correct solution, and if this will work for other CESM workflows.

### LINKED ISSUE #58: Compilation fails when requesting a compset that uses CTSM
### What happened?

Compilation fails when requesting a compset that uses CTSM.  There is an inconsistency between the latest CMEPS version and the StormSPEED CTSM version.  Recommend bringing all externals up to the latest CESM alpha branch.

### What are the steps to reproduce the bug?

Compile an F2000climo case.

### What CAM tag were you using?

stormspeed branch head

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

_No response_

### Will you be addressing this bug yourself?

Yes

### Extra info

_No response_

### PR DESCRIPTION
**Pull request by jtruesdal**
This PR fixes issues #51 and #58.  An inconsistent set of externals resulted in a compilation error for any compset using CTSM.  Additionally it fixes some critical bugs to allow restart testing and IC generation.  I updated the CAM externals to the set used in the latest alpha tag cesm3_0_alpha07c. Since that alpha tag used cam6_4_100 I've also updated the stormspeed CAM version. I've used a fork of the ccs_config_cesm1.0.57 to keep the external versions consistent with the alpha tag.  After this PR I'll look into making the non hydrostatic changes in a follow on PR to ccs_config.

The bug fixes and inconsistency mods are in .gitmodules, dyn_comp.F90, stepon.F90 and dp_coupling.F90.  The rest of the 70 some files were modified automatically when CAM was updated to cam6_4_100.  I ran a few bob start/restart and IC creation runs to make sure everything compiled and ran correctly.

closes Issue #51
closes Issue #58

### CODE REVIEW

**Comment by jtruesdal** [comment]
@sjsprecious Here is the update to stormspeed.  Lots of files but the only code I change is listed in the description above.  The rest of the changes are due to updating to cam6_4_100 to be consistent with the alpha tag set of externals.  After this is merged I'll update the refmesh mods and ask for your re-review on that PR.

File: src/dynamics/senh/stepon.F90 [hunk 1]
```diff
@@ -783,81 +748,35 @@ subroutine diag_dynvar_ic(elem)
...
+                    elem(ie)%state%dp3d(:,:,:,tl_f), (/npsq,nlev/)), npsq, ie)
+            else
+               call outfld(trim(cnst_name(m_cnst))//'&IC', &
+                    RESHAPE(elem(ie)%state%Qdp(:,:,:,m_cnst,tl_qdp)/&
+                    elem(ie)%state%dp3d(:,:,:,tl_f), (/npsq,nlev/)), npsq, ie)
+            end if
+         end do
       end do
 
 !!$      if (fv_nphys > 0) then
```
Comment (sjsprecious) [inline src/dynamics/senh/stepon.F90]: remove this line if not needed.

File: src/dynamics/senh/stepon.F90 [hunk 2]
```diff
@@ -783,81 +748,35 @@ subroutine diag_dynvar_ic(elem)
...
-!!$
-!!$            do ie = nets, nete
-!!$               call outfld(trim(cnst_name(m_cnst))//'&IC', &
-!!$                    RESHAPE(fld_gll(:,:,:,:,ie), (/npsq,nlev/)), npsq, ie)
-!!$            end do
-!!$         end do
-!!$
-!!$         deallocate(fld_fvm)
-!!$         deallocate(fld_gll)
 !!$      end if
```
Comment (sjsprecious) [inline src/dynamics/senh/stepon.F90]: remove this line if not needed.

File: src/dynamics/senh/dyn_comp.F90 [hunk 3]
```diff
@@ -756,53 +756,86 @@ end subroutine dyn_register
...
+       dyn_out%elem => elem
+    else
+       nullify(dyn_in%elem)
+       nullify(dyn_out%elem)
+    end if
 
-   call set_phis(dyn_in)
+    !jt   ! Create mapping files using SE basis functions if requested
+    !jt   call create_native_mapping_files(par, elem, 'native')
+    !jt   call create_native_mapping_files(par, elem, 'bilin')
```
Comment (sjsprecious) [inline src/dynamics/senh/dyn_comp.F90]: remove these lines if not needed.

**Review by sjsprecious — CHANGES_REQUESTED** [review]
Thanks @jtruesdal for working on these bug fixes and CAM tag update.

I only have some minor comments but it looks like the CI tests failed with a compilation error. Can you take a look and resolve them?

**Comment by jtruesdal** [comment]
Updated dyn_comp.F90 so it is building and cleaned up some commented code. I'll have to take some time now and go back through the remaining comments and start checking if that code needs to be incorporated.  SCM functionality is some of the code commented out so will work on that soon.  

 **_I noticed some of the CI tests failing because it was looking for datasets in /glade/inputdata instead of /glade/p/cesmdata/inputdata._**. Is this an error in the code or the CI scripts?  I don't think I changed the file that a few of the tests are missing but I guess it could have been updated with the move to cam6_4_100.

**Comment by sjsprecious** [comment]
> Updated dyn_comp.F90 so it is building and cleaned up some commented code. I'll have to take some time now and go back through the remaining comments and start checking if that code needs to be incorporated. SCM functionality is some of the code commented out so will work on that soon.

Thanks @jtruesdal for fixing this quickly.
 
> **_I noticed some of the CI tests failing because it was looking for datasets in /glade/inputdata instead of /glade/p/cesmdata/inputdata._**. Is this an error in the code or the CI scripts? I don't think I changed the file that a few of the tests are missing but I guess it could have been updated with the move to cam6_4_100.

The `/glade/p/cesmdata` path on Derecho is mounted to the `/glade` path in the container, so this should be fine. I think the problem is that the cloud runner can not find those files somehow and therefore it tried to download them. This is not possible since the cloud runner only has read access to the GLADE filesystem. I checked the `/glade/p/cesmdata` path on Derecho and files are there. But the date is quite recent so I think you are right that they may be updated and we need to refresh the path mounted to the cloud runner (not sure why we need to). I tested your PR manually on Derecho and it ran fine. Thus I will approve it and let you decide whether to merge it quickly or wait until the admin fixes the path/file issue (I will talk to him on Monday).

**Review by sjsprecious — APPROVED** [review]
Thanks @jtruesdal for addressing my comments. I will talk with the cloud admin about the path/file issue for the input data.

I see this git-fleximod test fails as well (https://github.com/NCAR/StormSPEED/actions/runs/17692143350/job/50287146200?pr=59) and I do not know if you can fix it or not. But it does not seem to touch any code changes here.
