### PR TITLE
Fix the restart issue at ne1024 resolution

### LINKED ISSUE #70: Failure of restart function at ne1024 resolution
### What happened?

When I ran the latest `stormspeed` branch on Derecho's CPU nodes (FADIAB test, ne1024 resolution, 200 full CPU nodes), it failed at the `pio_initdecomp` subroutine call from https://github.com/NCAR/StormSPEED/blob/stormspeed/src/dynamics/senh/restart_dynamics.F90#L320.

The error message looks like:
```
dec0631.hsn.de.hpc.ucar.edu 10625: forrtl: severe (174): SIGSEGV, segmentation fault occurred
dec0631.hsn.de.hpc.ucar.edu 10625: Image              PC                Routine            Line        Source             
dec0631.hsn.de.hpc.ucar.edu 10625: libc.so.6          000014B557842900  Unknown               Unknown  Unknown
dec0631.hsn.de.hpc.ucar.edu 10625: libpioc.so         000014B564C250ED  subset_rearrange_     Unknown  Unknown
dec0631.hsn.de.hpc.ucar.edu 10625: libpioc.so         000014B564C19557  PIOc_InitDecomp       Unknown  Unknown
dec0631.hsn.de.hpc.ucar.edu 10625: libpiof.so         000014B565015904  piolib_mod_mp_pio     Unknown  Unknown
dec0631.hsn.de.hpc.ucar.edu 10625: libpiof.so         000014B565016B89  piolib_mod_mp_pio     Unknown  Unknown
dec0631.hsn.de.hpc.ucar.edu 10625: libpiof.so         000014B56501524C  piolib_mod_mp_pio     Unknown  Unknown
dec0631.hsn.de.hpc.ucar.edu 10625: cesm.exe           0000000000706BEC  restart_dynamicsw         326  restart_dynamics.F90
dec0631.hsn.de.hpc.ucar.edu 10625: cesm.exe           0000000000705C4F  restart_dynamics_         237  restart_dynamics.F90
dec0631.hsn.de.hpc.ucar.edu 10625: cesm.exe           00000000004D3B12  cam_restart_mp_ca         127  cam_restart.F90
dec0631.hsn.de.hpc.ucar.edu 10625: cesm.exe           000000000046DAA8  cam_comp_mp_cam_r         388  cam_comp.F90
dec0631.hsn.de.hpc.ucar.edu 10625: cesm.exe           0000000000449F3C  atm_comp_nuopc_mp        1153  atm_comp_nuopc.F90
```

I checked the job status. I requested 47 TB memory in total but only 14 TB memory was used before the job crashed. Thus I think this is less likely an exceeding memory issue.

I later found that Mark Taylor reported a similar error back in 2019 for both HOMME (https://github.com/E3SM-Project/E3SM/issues/2697) and EAM (https://github.com/E3SM-Project/E3SM/issues/2698). And the fix was to make some variables as 64-bit integers (https://github.com/E3SM-Project/E3SM/pull/2699). When we go to further higher resolution, more changes to 64-bit integer variables may be needed (https://github.com/E3SM-Project/E3SM/issues/4763).

On the CAM physics end, some changes are needed to avoid an integer overflow as well, as reported by Matt Norman (https://github.com/E3SM-Project/ACME-ECP/pull/77).

I could confirm that the same branch ran successfully at ne512 resolution. Therefore, I suspected that we hit a similar error as Mark did in HOMME/EAM.

### What are the steps to reproduce the bug?

Run the `stormspeed` branch at ne1024 resolution and turn on the restart output.

### What CAM tag were you using?

stormspeed

### What machine were you running CAM on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

Intel

### Path to a case directory, if applicable

_No response_

### Will you be addressing this bug yourself?

Yes, but I will need some help

### Extra info

_No response_

### PR DESCRIPTION
**Pull request by sjsprecious**
This pull request fixes the restart issue when running FADIAB compset at ne1024 resolution due to an integer overflow.

Basically we need to define the `ldof` variable as 64-bit integer and convert the calculation of its value to 64-bit integer as well before the assignment.

We also update the SE-NH dycore version to include our previous GPU code fix (https://github.com/E3SM-Project/E3SM/pull/7668).

fix #70

### CODE REVIEW

File: .gitmodules [hunk 1]
```diff
@@ -217,5 +217,5 @@ path = src/dynamics/senh/dycore
 url = https://github.com/E3SM-Project/E3SM.git
 fxrequired = AlwaysRequired
 fxsparse = ../.e3sm_sparse_checkout
-fxtag = cec3bb6
+fxtag = 057df66
```
Comment (jtruesdal) [inline .gitmodules:220]: Did you check the dycore files we have in cam_mods against the updates in this tag?

File: src/utils/cam_map_utils.F90 [hunk 2]
```diff
@@ -689,7 +689,7 @@ subroutine cam_filemap_get_filemap(this, fieldlens, filelens, filemap,      &
     end if
 
     ! Allocate output filemap (dof)
-    allocate(filemap(product(fieldlens)))
+    allocate(filemap(product( int(fieldlens,kind=iMap) )))
```
Comment (jtruesdal) [inline src/utils/cam_map_utils.F90]: We are slowly adding status checks to the allocate statements when we create or modify one.

**Review by jtruesdal — APPROVED** [review]
Nice work tracking these down and fixing/optimizing the loops with overflows to move the invariants to the base variable. I have one change and also wanted to make sure you checked the code in cam_mods against the theta-l dycore updates.

File: .gitmodules (hunk 1 above)
Comment (sjsprecious) [reply .gitmodules:220]: Yes, it is tested and does not show any conflict yet.

File: src/utils/cam_map_utils.F90 (hunk 2 above)
Comment (sjsprecious) [reply src/utils/cam_map_utils.F90]: Thanks. The allocate statement check is added.
